### ISSUE TITLE
DI fails on AddFluentValidationRulesToSwagger when using Custom Validator on-demand instantiation

### ISSUE THREAD

**Issue by kada-vkw** [micro-elements/MicroElements.Swashbuckle.FluentValidation#117]
### FluentValidation version

11.1.0

### ASP.NET version

.NET 6

### Summary

I am using `services.AddFluentValidationRulesToSwagger();` in my Startup and I do use Custom Validators, which are created on-demand, so I can pass data to a validator via constructor.

I am using this approach from [here](https://stackoverflow.com/questions/61550275/fluentvalidation-using-a-parent-property-value-in-a-child-collection-rule) to pass data from parent validator to a child validator.
```c#
public class MyTypeValidator: AbstractValidator<MyType>
{
    public LoadValidator(PassedParameterType inputData)
    { 
       ... some more rules based on inputData
    }
}

public class ContainerClassValidator: AbstractValidator<ContainerClss>
{
    public ContainerClassValidator()
    {
        RuleForEach(containerData=> containerData.MyTypeObjects).SetValidator(containerData => new MyTypeValidator(containerData.passDataAsParameter));
    }
}
```
`AddFluentValidationRulesToSwagger` uses some kind of assembly scanning (i guess) to gather the necessary data for creating validation rules in swagger.
This leads to a exception when trying to instantiate the validator with constructor custom parameters (since the passed param data cannot be found by DI)

Since the on-demand Validators should, and cannot, be instantiated via DI (because of the parameter not available to DI) I get exceptions on startup of the program.

Stacktrace:
```
GetValidator for type 'MyType' fails.
System.InvalidOperationException: Unable to resolve service for type 'PassedParameterType' while attempting to activate 'MyTypeValidator'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at MicroElements.Swashbuckle.FluentValidation.ServiceProviderValidatorRegistry.GetValidator(Type type) in /home/runner/work/MicroElements.Swashbuckle.FluentValidation/MicroElements.Swashbuckle.FluentValidation/src/MicroElements.Swashbuckle.FluentValidation/FluentValidation/ServiceProviderValidatorRegistry.cs:line 22
   at MicroElements.Swashbuckle.FluentValidation.FluentValidationRules.Apply(OpenApiSchema schema, SchemaFilterContext context) in /home/runner/work/MicroElements.Swashbuckle.FluentValidation/MicroElements.Swashbuckle.FluentValidation/src/MicroElements.Swashbuckle.FluentValidation/Swashbuckle/FluentValidationRules.cs:line 91
```

When I skip the exceptions and let the program run, then no more exceptions occur - validation works as expected.

The effectively shown exception in the IDE is a `NullpointerException` when DI tries to resolve the lambda function to create the constructor parameter `SetValidator(containerData => new MyTypeValidator(containerData.passDataAsParameter))` since containerData is null and accessing a member throws.

### Steps to Reproduce

Create a Validation Setup as above, where a child validator uses data from constructor parameters.

Add AddFluentValidationRulesToSwagger in your Startup

Startup progam leads to exception as described

**Comment by petriashev** [comment]
You also need to register validators and their dependencies.
`PassedParameterType` can not be retrieved from serviceProvider 
Can you provide more detailed example with registration stuff?

**Comment by kada-v** [comment]
I do use a dotnet 6 web api project and I do register my services manually like so
```c#
'Startup.cs
services.AddScoped<IMyService, MyService>();
```
for validation things I use 
```c#
services.AddControllers()
            .AddFluentValidation(fv => fv.RegisterValidatorsFromAssemblyContaining<Startup>())
```
Optionally you could add a filtering method to skip some Validators from being registered. But `AddFluentValidationRulesToSwagger` does not respect this filtering as stated above.

**Comment by petriashev** [comment]
Can you provide more detailed example with registration stuff? link to example repository?
`AddFluentValidationRulesToSwagger` uses validator that you registered in services. There are some differences for FV versions
