### ISSUE TITLE
Got some warning messages with NullReferenceException in Kestrel console

### ISSUE THREAD

**Issue by xiaoyumu** [micro-elements/MicroElements.Swashbuckle.FluentValidation#13]
Hi @petriashev,

When I using ```MicroElements.Swashbuckle.FluentValidation``` 0.8.1 with ```FluentValidation``` 7.6.103 and ```Swashbuckle.FluentValidation``` 2.5.0 in my ASP.NET Core 2.1 WebApi project, adding validation related description in swagger may causing some warning message in the Kestrel console. Everything else is fine, the swagger UI still works , and validation description still showed up in model section.

```
warn: MicroElements.Swashbuckle.FluentValidation.FluentValidationRules[0]
      Error on apply rules for operation 'ConfigurationSystem-configGet'.
System.NullReferenceException: Object reference not set to an instance of an object.
   at MicroElements.Swashbuckle.FluentValidation.FluentValidationOperationFilter.ApplyInternal(Operation operation, OperationFilterContext context) in /home/travis/build/micro-elements/MicroElements.Swashbuckle.FluentValidation/src/MicroElements.Swashbuckle.FluentValidation/FluentValidationOperationFilter.cs:line 106
   at MicroElements.Swashbuckle.FluentValidation.FluentValidationOperationFilter.Apply(Operation operation, OperationFilterContext context) in /home/travis/build/micro-elements/MicroElements.Swashbuckle.FluentValidation/src/MicroElements.Swashbuckle.FluentValidation/FluentValidationOperationFilter.cs:line 47
```

It seems in some cases, the ```schema.Properties``` might be null, maybe it's better to check it before use it?

```cs
// My rule is very simple, the ID is a Nullable<int>.
RuleFor(r => r.ID).NotNull();
```
If adding ```schema.Properties != null``` this to the schema null check, the warning message goes away.
```cs
if (schema !=null && schema.Properties != null)
{
	if (operationParameter is PartialSchema partialSchema)
	{
		if (schema.Properties.TryGetValue(key.ToLowerCamelCase(), out var property) 
			|| schema.Properties.TryGetValue(key, out property))
		{
			partialSchema.MinLength = property.MinLength;
			partialSchema.MaxLength = property.MaxLength;
			partialSchema.Pattern = property.Pattern;
			partialSchema.Minimum = property.Minimum;
			partialSchema.Maximum = property.Maximum;
			partialSchema.ExclusiveMaximum = property.ExclusiveMaximum;
			partialSchema.ExclusiveMinimum = property.ExclusiveMinimum;
		}
	}
}
```

**Comment by petriashev** [comment]
try 0.8.2
