### ISSUE TITLE
Support Swagger v5

### ISSUE THREAD

**Issue by petriashev** [micro-elements/MicroElements.Swashbuckle.FluentValidation#25]
Swashbuckle.AspNetCore 5.0.0-beta does not work with MicroElements.Swashbuckle.FluentValidation.

- Add support to v5
- Restrict version MicroElements.Swashbuckle.FluentValidation to Swashbuckle.AspNetCore < v5

**Comment by robertmiles3** [comment]
Any ETA on this? Would love to use this. Let me know if I can help in any way.

**Comment by petriashev** [comment]
I will ship alpha release soon

**Comment by petriashev** [comment]
I need help with tests - welcome!)

**Comment by petriashev** [comment]
See https://www.nuget.org/packages/MicroElements.Swashbuckle.FluentValidation/3.0.0-alpha.1

**Comment by robertmiles3** [comment]
Using this alpha and Swashbuckle.AspNetCore 5.0.0-rc2, I'm getting this when I plug it in and try to load the docs page...

```System.MissingMethodException: Method not found: 'System.Type Swashbuckle.AspNetCore.SwaggerGen.SchemaFilterContext.get_SystemType()'.```

**Comment by petriashev** [comment]
fixing. there was many breaking changes in rc

**Comment by petriashev** [comment]
see https://www.nuget.org/packages/MicroElements.Swashbuckle.FluentValidation/3.0.0-beta.1

**Comment by Hawxy** [comment]
@petriashev fyi Swashbuckle RC.3 is out and this is broken again.

**Comment by vova-lantsov-dev** [comment]
@petriashev 
```
 System.MissingMethodException: Method not found: 'System.Type Swashbuckle.AspNetCore.SwaggerGen.SchemaFilterContext.get_Type()'.
   at MicroElements.Swashbuckle.FluentValidation.FluentValidationRules.Apply(OpenApiSchema schema, SchemaFilterContext context)
   at Swashbuckle.AspNetCore.SwaggerGen.ApiModelHandler.GenerateDefinitionSchemaAndApplyFilters(ApiModel apiModel, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.ApiModelHandler.GenerateSchema(ApiModel apiModel, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.ApiModelHandler.GenerateSchema(ApiModel apiModel, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.ApiModelHandler.GenerateSchema(ApiModel apiModel, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateParameter(ApiParameterDescription apiParameter, SchemaRepository schemaRepository)
   at System.Linq.Enumerable.WhereSelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperation(ApiDescription apiDescription, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GenerateOperations(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GeneratePaths(IEnumerable`1 apiDescriptions, SchemaRepository schemaRepository)
   at Swashbuckle.AspNetCore.SwaggerGen.SwaggerGenerator.GetSwagger(String documentName, String host, String basePath)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.MigrationsEndPointMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore.DatabaseErrorPageMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by vova-lantsov-dev** [comment]
@petriashev @Hawxy okay, i made it work, see my pull request https://github.com/micro-elements/MicroElements.Swashbuckle.FluentValidation/pull/35
