### ISSUE TITLE
Library doesn't work with Swashbuckle 5.0.0

### ISSUE THREAD

**Issue by chester89** [micro-elements/MicroElements.Swashbuckle.FluentValidation#52]
Your nuget dependency restrictions say Swashbuckle version must be lower than 5. 
So when I try to use it with version 5.0.0, application breaks

```
FATAL Microsoft.AspNetCore.Hosting.Diagnostics Application startup exception System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Method 'Apply' in type 'MicroElements.Swashbuckle.FluentValidation.FluentValidationOperationFilter' from assembly 'MicroElements.Swashbuckle.FluentValidation, Version=2.3.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'Apply' in type 'MicroElements.Swashbuckle.FluentValidation.FluentValidationRules' from assembly 'MicroElements.Swashbuckle.FluentValidation, Version=2.3.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at Microsoft.AspNetCore.Mvc.ApplicationParts.AssemblyPart.get_Types()
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFeatureProvider.PopulateFeature(IEnumerable`1 parts, ControllerFeature feature)
   at Microsoft.AspNetCore.Mvc.ApplicationParts.ApplicationPartManager.PopulateFeature[TFeature](TFeature feature)
   at Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerActionDescriptorProvider.GetControllerTypes()
   at Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerActionDescriptorProvider.GetDescriptors()
   at Microsoft.AspNetCore.Mvc.ApplicationModels.ControllerActionDescriptorProvider.OnProvidersExecuting(ActionDescriptorProviderContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.UpdateCollection()
   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.Initialize()
   at Microsoft.AspNetCore.Mvc.Infrastructure.DefaultActionDescriptorCollectionProvider.GetChangeToken()
   at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointDataSourceBase.<>c__DisplayClass11_0.<Subscribe>b__0()
   at Microsoft.Extensions.Primitives.ChangeToken.ChangeTokenRegistration`1..ctor(Func`1 changeTokenProducer, Action`1 changeTokenConsumer, TState state)
   at Microsoft.Extensions.Primitives.ChangeToken.OnChange(Func`1 changeTokenProducer, Action changeTokenConsumer)
   at Microsoft.AspNetCore.Mvc.Routing.ActionEndpointDataSourceBase.Subscribe()
   at Microsoft.AspNetCore.Mvc.Routing.ControllerActionEndpointDataSource..ctor(IActionDescriptorCollectionProvider actions, ActionEndpointFactory endpointFactory)

```

Can you release a new version?
I use .NET Core 3.1

**Comment by chester89** [comment]
I see you released 3.0.0 recently, after updating the app works as detected. thanks
