### ISSUE TITLE
Missing method exception when using Swashbuckle > 5.0.0

### ISSUE THREAD

**Issue by bajdka** [micro-elements/MicroElements.Swashbuckle.FluentValidation#53]
Exception is thrown when trying to generate Swagger schema with following setup:

- **MicroElements.Swashbuckle.FluentValidation** Version=**3.0.0-beta.1**

- **Swashbuckle.AspNetCore** Version=**5.2.0**

Issue doesn't exist when Swashbuckle.AspNetCore 5.0.0 is used.

```
warn: MicroElements.Swashbuckle.FluentValidation.FluentValidationRules[0]
      Error on apply rules for operation ''.
System.MissingMethodException: Method not found: 'Void Swashbuckle.AspNetCore.SwaggerGen.SchemaFilterContext..ctor(System.Type, Newtonsoft.Json.Serialization.JsonContract, Swashbuckle.AspNetCore.SwaggerGen.SchemaRepository, Swashbuckle.AspNetCore.SwaggerGen.ISchemaGenerator)'.
   at MicroElements.Swashbuckle.FluentValidation.FluentValidationOperationFilter.ApplyInternal(OpenApiOperation operation, OperationFilterContext context)
   at MicroElements.Swashbuckle.FluentValidation.FluentValidationOperationFilter.Apply(OpenApiOperation operation, OperationFilterContext context) in /home/travis/build/micro-elements/MicroElements.Swashbuckle.FluentValidation/src/MicroElements.Swashbuckle.FluentValidation/FluentValidationOperationFilter.cs:line 52
```

**Comment by jufa2401** [comment]
I have the same issue

`System.MissingMethodException: Method not found: 'Void Swashbuckle.AspNetCore.SwaggerGen.SchemaFilterContext..ctor(System.Type, Swashbuckle.AspNetCore.SwaggerGen.SchemaRepository, Swashbuckle.AspNetCore.SwaggerGen.ISchemaGenerator)'.
   at MicroElements.Swashbuckle.FluentValidation.FluentValidationOperationFilter.ApplyInternal(OpenApiOperation operation, OperationFilterContext context)
   at MicroElements.Swashbuckle.FluentValidation.FluentValidationOperationFilter.Apply(OpenApiOperation operation, OperationFilterContext context) in /home/travis/build/micro-elements/MicroElements.Swashbuckle.FluentValidation/src/MicroElements.Swashbuckle.FluentValidation/FluentValidationOperationFilter.cs:line 49
[12:34:04 WRN] Error on apply rules for operation ''.
System.MissingMethodException: Method not found: 'Void Swashbuckle.AspNetCore.SwaggerGen.SchemaFilterContext..ctor(System.Type, Swashbuckle.AspNetCore.SwaggerGen.SchemaRepository, Swashbuckle.AspNetCore.SwaggerGen.ISchemaGenerator)'.
   at MicroElements.Swashbuckle.FluentValidation.FluentValidationOperationFilter.ApplyInternal(OpenApiOperation operation, OperationFilterContext context)
   at MicroElements.Swashbuckle.FluentValidation.FluentValidationOperationFilter.Apply(OpenApiOperation operation, OperationFilterContext context) in /home/travis/build/micro-elements/MicroElements.Swashbuckle.FluentValidation/src/MicroElements.Swashbuckle.FluentValidation/FluentValidationOperationFilter.cs:line 49
[12:34:04 WRN] Error on apply rules for operation ''.
System.MissingMethodException: Method not found: 'Void Swashbuckle.AspNetCore.SwaggerGen.SchemaFilterContext..ctor(System.Type, Swashbuckle.AspNetCore.SwaggerGen.SchemaRepository, Swashbuckle.AspNetCore.SwaggerGen.ISchemaGenerator)'.
   at MicroElements.Swashbuckle.FluentValidation.FluentValidationOperationFilter.ApplyInternal(OpenApiOperation operation, OperationFilterContext context)
   at MicroElements.Swashbuckle.FluentValidation.FluentValidationOperationFilter.Apply(OpenApiOperation operation, OperationFilterContext context) in /home/travis/build/micro-elements/MicroElements.Swashbuckle.FluentValidation/src/MicroElements.Swashbuckle.FluentValidation/FluentValidationOperationFilter.cs:line 49
[12:34:04 WRN] Error on apply rules for operation ''.
System.MissingMethodException: Method not found: 'Void Swashbuckle.AspNetCore.SwaggerGen.SchemaFilterContext..ctor(System.Type, Swashbuckle.AspNetCore.SwaggerGen.SchemaRepository, Swashbuckle.AspNetCore.SwaggerGen.ISchemaGenerator)'.
   at MicroElements.Swashbuckle.FluentValidation.FluentValidationOperationFilter.ApplyInternal(OpenApiOperation operation, OperationFilterContext context)
   at MicroElements.Swashbuckle.FluentValidation.FluentValidationOperationFilter.Apply(OpenApiOperation operation, OperationFilterContext context) in /home/travis/build/micro-elements/MicroElements.Swashbuckle.FluentValidation/src/MicroElements.Swashbuckle.FluentValidation/FluentValidationOperationFilter.cs:line 49
[12:34:04 INF] Request finished in 464.2773ms 200 application/json;charset=utf-8


`

**Comment by jufa2401** [comment]
I am no longer experiencing the issue after new version 3.1.0
