### ISSUE TITLE
Exceptions during startup for polymorphic types

### ISSUE THREAD

**Issue by ErikPilsits-RJW** [micro-elements/MicroElements.Swashbuckle.FluentValidation#73]
I'm getting the following exception during application startup for polymorphic types. I don't have time right now to try and mock something reproducible, but let me know if this is enough to get you started.

This exception is the derived type, but I also get a very similar exception for the base type, QueryBuilderBase.

```
[2021-01-26 18:35:05.495] [WRN] [MicroElements.Swashbuckle.FluentValidation.FluentValidationRules] [R:80000026-0000-fe00-b63f-84710c7967bb|T:cfb2b7e2dec6de49bd5c0d020c65d981|S:30ccdb394b7e8940] Applying IncludeRules for type 'QueryBuilder.Models.QueryBuilderQuery' fails.
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at FluentValidation.Validators.PropertyValidatorContext.get_PropertyValue() in /home/jskinner/code/FluentValidation/src/FluentValidation/Validators/PropertyValidatorContext.cs:line 52
   at FluentValidation.Validators.PolymorphicValidator`2.GetValidator(PropertyValidatorContext context) in /home/jskinner/code/FluentValidation/src/FluentValidation/Validators/PolymorphicValidator.cs:line 103
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at MicroElements.Swashbuckle.FluentValidation.FluentValidationSchemaBuilder.GetValidatorFromChildValidatorAdapter(IChildValidatorAdaptor childValidatorAdapter) in /home/runner/work/MicroElements.Swashbuckle.FluentValidation/MicroElements.Swashbuckle.FluentValidation/src/MicroElements.Swashbuckle.FluentValidation/FluentValidationSchemaBuilder.cs:line 140
   at MicroElements.Swashbuckle.FluentValidation.FluentValidationSchemaBuilder.AddRulesFromIncludedValidators(OpenApiSchema schema, SchemaFilterContext schemaFilterContext, IValidator validator, IReadOnlyCollection`1 rules, ILogger logger) in /home/runner/work/MicroElements.Swashbuckle.FluentValidation/MicroElements.Swashbuckle.FluentValidation/src/MicroElements.Swashbuckle.FluentValidation/FluentValidationSchemaBuilder.cs:line 106
   at MicroElements.Swashbuckle.FluentValidation.FluentValidationSchemaBuilder.AddRulesFromIncludedValidators(OpenApiSchema schema, SchemaFilterContext schemaFilterContext, IValidator validator, IReadOnlyCollection`1 rules, ILogger logger) in /home/runner/work/MicroElements.Swashbuckle.FluentValidation/MicroElements.Swashbuckle.FluentValidation/src/MicroElements.Swashbuckle.FluentValidation/FluentValidationSchemaBuilder.cs:line 106
   at MicroElements.Swashbuckle.FluentValidation.FluentValidationRules.AddRulesFromIncludedValidators(OpenApiSchema schema, SchemaFilterContext context, IValidator validator) in /home/runner/work/MicroElements.Swashbuckle.FluentValidation/MicroElements.Swashbuckle.FluentValidation/src/MicroElements.Swashbuckle.FluentValidation/FluentValidationRules.cs:line 96
   at MicroElements.Swashbuckle.FluentValidation.FluentValidationRules.Apply(OpenApiSchema schema, SchemaFilterContext context) in /home/runner/work/MicroElements.Swashbuckle.FluentValidation/MicroElements.Swashbuckle.FluentValidation/src/MicroElements.Swashbuckle.FluentValidation/FluentValidationRules.cs:line 68
```

**Comment by ErikPilsits-RJW** [comment]
Ok, bit more info. My base class is using the JsonSubtypes nuget to help build the correct swagger. FilterType is an enum.
```
[JsonConverter(typeof(JsonSubtypes), "Type")]
[JsonSubtypes.KnownSubType(typeof(StringFilter), FilterType.String)]
[JsonSubtypes.KnownSubType(typeof(NumberFilter), FilterType.Number)]
[JsonSubtypes.KnownSubType(typeof(DateFilter), FilterType.Date)]
public abstract class BaseFilter
```

Then I'm using the following in startup. BaseFilter is the base class, and String/Number/DateFilter are the derived types (above).
```
c.UseOneOfForPolymorphism();
c.SelectSubTypesUsing(baseType => baseType.Assembly.GetTypes().Where(t =>
    baseType == typeof(BaseFilter)
    && t.IsSubclassOf(baseType)
    && !t.IsGenericType));
c.SelectDiscriminatorNameUsing(baseType => "Type");
c.SelectDiscriminatorValueUsing(subType => subType.Name.Replace("Filter", ""));
```

**Comment by ErikPilsits-RJW** [comment]
Can I help with any more info on this issue? It's still happening with version 4.3.0 of this package, swashbuckle version 6.1.3, and fluent validation version 9.5.4.

**Comment by petriashev** [comment]
PR welcome!
Have no time untill holidays in May

**Comment by petriashev** [comment]
Can you add sample in SampleWebApp or test?

**Comment by ErikPilsits-RJW** [comment]
Yeah I'll see if I can't add something in SampleWebApi (App?) to repro and send you a PR. Might be next week.
