### ISSUE TITLE
(5.0.0-rc.1) DOTNET_ENVIRONMENT=Development causes exception

### ISSUE THREAD

**Issue by mbp** [micro-elements/MicroElements.Swashbuckle.FluentValidation#83]
If you use the library (latest version) when using environment variable `DOTNET_ENVIRONMENT=Development`, then the following exception occurs:

```
System.InvalidOperationException: Cannot resolve scoped service 'FluentValidation.IValidatorFactory' from root provider.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteValidator.ValidateResolution(Type serviceType, IServiceScope scope, IServiceScope rootScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceProviderEngineCallback.OnResolve(Type serviceType, IServiceScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Swashbuckle.AspNetCore.SwaggerGen.ConfigureSwaggerGeneratorOptions.CreateFilter[TFilter](FilterDescriptor filterDescriptor)
   at Swashbuckle.AspNetCore.SwaggerGen.ConfigureSwaggerGeneratorOptions.<>c__DisplayClass4_0.<Configure>b__2(FilterDescriptor filterDescriptor)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Swashbuckle.AspNetCore.SwaggerGen.ConfigureSwaggerGeneratorOptions.Configure(SwaggerGeneratorOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.OptionsManager`1.<>c__DisplayClass5_0.<Get>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   [...]
```
   
This is reproducible with the "SampleWebApi" included in this repository.
I simply upgraded the dependencies, `FluentValidation.AspNetCore` 9.1.3 =>10.0.1, `Swashbuckle.AspNetCore.SwaggerUI` 6.0.0 => 6.1.4.
   
And ran it with:
   
```
DOTNET_ENVIRONMENT=Development dotnet run
```

And visited `/swagger/v1/swagger.yaml` in the browser.

**Comment by petriashev** [comment]
AddSwaggerGen registers SchemaGeneratorOptions as Transient, filters created on the same service provider:
`services.AddTransient<IConfigureOptions<SchemaGeneratorOptions>, ConfigureSchemaGeneratorOptions>();`

FV registers IValidatorFactory as scoped:
`services.Add(ServiceDescriptor.Scoped(s => factory));`

so scope conflict occures

Workaround 1
Try add in Program.cs ValidateScopes = false
```
  Host.CreateDefaultBuilder(args)
      .UseDefaultServiceProvider(options => options.ValidateScopes = false)
```
Workaround 2
In AddFluentValidation replace c.ValidatorFactoryType with c.ValidatorFactory (if possible to create in on Startup)

**Comment by petriashev** [comment]
sample migrate to fv10 completed

**Comment by mbp** [comment]
@petriashev thank you, I think you didn't push the sample migration :) Curious to see which workaround you used :-)

**Comment by petriashev** [comment]
sorry :) I have pushed it now

**Comment by mbp** [comment]
It's good to have the workaround, but I wonder if it could be solved in a proper way.

**Comment by petriashev** [comment]
I think that proper way is to change how Swagger registers their services (see code for AddSwaggerGen).
Or change registration for FV. But at this moment there no way to do it without some hacks

**Comment by Keen83** [comment]
Could you explain second workaround a bit more?

**Comment by petriashev** [comment]
Added registration hack in 5.1.0
Please try 5.1.0-rc.1

**Comment by petriashev** [comment]
Good article about scope and IOptions: https://andrewlock.net/the-dangers-and-gotchas-of-using-scoped-services-when-configuring-options-in-asp-net-core/
