### ISSUE TITLE
(5.0.0-rc.1) Method not found exception with Swashbuckle.AspNetCore version 6.0.2 and later

### ISSUE THREAD

**Issue by tijmenpitcrew** [micro-elements/MicroElements.Swashbuckle.FluentValidation#85]
A method not found exception will be raised when generating the OpenAPI specifications. This is in combination with an ASP.NET Core 3.1 project using:
- MicroElements.Swashbuckle.FluentValidation 5.0.0-rc1
- FluentValidation.AspNetCore 10.0.1
- Swashbuckle.AspNetCore 6.1.4 (latest) down to 6.0.2

The problem is this revert https://github.com/domaindrivendev/Swashbuckle.AspNetCore/commit/4331154ab9c4ff58da8cf7ff5f666d59fcd8c855 . Downgrading temporarily to Swashbuckle.AspNetCore 6.0.1 fixes this issue.

The resulting stack trace tells you that it is looking for an `IDictionary` whilst the actual type in 6.0.2 and later is `Dictionary`. I unfortunately no longer that said stack trace as I decided a little late to report my issue here.

**Comment by akatakritos** [comment]
```
[2021-05-18 09:57:22.04 MicroElements.Swashbuckle.FluentValidation.FluentValidationRules WRN] Applying IncludeRules for type '**REDACTED**' fails.
System.MissingMethodException: Method not found: 'System.Collections.Generic.IDictionary`2<System.String,Microsoft.OpenApi.Models.OpenApiSchema> Swashbuckle.AspNetCore.SwaggerGen.SchemaRepository.get_Schemas()'.
   at MicroElements.Swashbuckle.FluentValidation.SwashbuckleSchemaProvider.GetSchemaForType(Type type)
   at MicroElements.Swashbuckle.FluentValidation.FluentValidationSchemaBuilder.AddRulesFromIncludedValidators(IValidator validator, ILogger logger, SchemaGenerationContext schemaGenerationContext) in /home/runner/work/MicroElements.Swashbuckle.FluentValidation/MicroElements.Swashbuckle.FluentValidation/src/MicroElements.Swashbuckle.FluentValidation/FluentValidationSchemaBuilder.cs:line 143
   at MicroElements.Swashbuckle.FluentValidation.FluentValidationRules.AddRulesFromIncludedValidators(SchemaFilterContext context, IValidator validator, SchemaGenerationContext schemaGenerationContext) in /home/runner/work/MicroElements.Swashbuckle.FluentValidation/MicroElements.Swashbuckle.FluentValidation/src/MicroElements.Swashbuckle.FluentValidation/Swashbuckle/FluentValidationRules.cs:line 133
   at MicroElements.Swashbuckle.FluentValidation.FluentValidationRules.Apply(OpenApiSchema schema, SchemaFilterContext context) in /home/runner/work/MicroElements.Swashbuckle.FluentValidation/MicroElements.Swashbuckle.FluentValidation/src/MicroElements.Swashbuckle.FluentValidation/Swashbuckle/FluentValidationRules.cs:line 113
```

I was actually on my way over to report this and see how I could help.

I'm on Swashbuckle.AspNetCore @ 6.1.2, MicroElements.Swashbuckle.FluentValidation @ 5.0.0-rc.1

**Comment by petriashev** [comment]
try https://www.nuget.org/packages/MicroElements.Swashbuckle.FluentValidation/5.0.0-rc.2

**Comment by akatakritos** [comment]
Thanks! I'm able to boot my app with no warnings on RC2, and I see validation data reflected in SwaggerUI.

**Comment by petriashev** [comment]
I assume that issue is closed
