### ISSUE TITLE
Version 5.1.0-rc.1 Failed to generate Operation for action.

### ISSUE THREAD

**Issue by rcollette** [micro-elements/MicroElements.Swashbuckle.FluentValidation#88]
I am running this rc due to #83 
I have updated to the latest releases of Swashbuckle packages.

I am getting the error.

```
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorException: Failed to generate Operation for action - Precisely.Pdx.Api.Web.Controllers.BulkSoftwareDeliveries.BulkSoftwareDeliveryController.Post (Precisely.Pdx.Api.Web). See inner exception
 ---> Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorException: Failed to generate schema for type - Precisely.Pdx.Api.Service.BulkSoftwareDeliveries.Model.BulkSoftwareDeliveryCreateModel. See inner exception
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at MicroElements.Swashbuckle.FluentValidation.FluentValidationRulesScopeAdapter.Apply(OpenApiSchema schema, SchemaFilterContext context) in /home/runner/work/MicroElements.Swashbuckle.FluentValidation/MicroElements.Swashbuckle.FluentValidation/src/MicroElements.Swashbuckle.FluentValidation/Swashbuckle/FluentValidationRulesScopeAdapter.cs:line 33
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.ApplyFilters(OpenApiSchema schema, Type type, SchemaRepository schemaRepository, MemberInfo memberInfo, ParameterInfo parameterInfo)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.GenerateSchemaForMember(Type modelType, SchemaRepository schemaRepository, MemberInfo memberInfo, DataProperty dataProperty)
   at Swashbuckle.AspNetCore.SwaggerGen.SchemaGenerator.CreateObjectSchema(DataContract dataContract, SchemaRepository schemaRepository)
```

My class is rather simple, except perhaps that it has a regular expression validation.

```c#
using System;
using System.ComponentModel.DataAnnotations;

namespace Precisely.Pdx.Api.Service.BulkSoftwareDeliveries.Model
{
    public class BulkSoftwareDeliveryCreateModel
    {
        [Required]
        [MinLength(3)]
        [MaxLength(100)]
        public string Name { get; set; } = null!;

        [MaxLength(255)]
        public string Description { get; set; } = null!;

        [Required]
        [MinLength(3)]
        [MaxLength(100)]
        public string ProductDeliveryGroupCode { get; set; } = null!;

        [Required]
        [RegularExpression(@"^((([0-9]{1,4})\.([0-9]{1,4})\.([0-9]{1,4})))$")]
        public string DisplayVersion { get; set; } = null!;

        [Required]
        public DateTime? ReleaseDate { get; set; } // Must be nullable/required to prevent a default value being used.

        public string? Languages { get; set; }

        public string? Platforms { get; set; }
    }
}

```

**Comment by petriashev** [comment]
Try to use new registration method (AddFluentValidationRulesToSwagger)

```csharp
// Adds FluentValidationRules staff to Swagger
services.AddFluentValidationRulesToSwagger();
```

I will add exception with a hint in next version. Thank you for issue

**Comment by rcollette** [comment]
That worked.  Thank you.

I guess the confusion here comes from:

1. No deprecation notice/annotation on AddFluentValidationRules (or perhaps it should even be removed because it does not work)
2. Changelog does not indicate a breaking change.

I'll leave the issue open for now assuming it will be addressed in the full 5.1 release.

Thanks again for all the hard work.  This is a very useful library.

**Comment by petriashev** [comment]
Please try rc.2

**Comment by rcollette** [comment]
Looks good to me.

![image](https://user-images.githubusercontent.com/136476/121091984-e08a4500-c7b8-11eb-9df4-10c55617c6c0.png)
