### ISSUE TITLE
Passing an object to an inheritance validator does not emit FluentValidation rules on property

### ISSUE THREAD

**Issue by icnocop** [micro-elements/MicroElements.Swashbuckle.FluentValidation#96]
Hi.

When I create a rule for a property which sets and passes an object to an inheritance validator, the FluentValidation rules for that property's type are not emitted in swagger.json.

For example, when not passing an object to an inheritance validator, the NotEmpty and MaxLength rules are emitted in swagger.json:
```
using FluentValidation;
using JetBrains.Annotations;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace SampleWebApi.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class IssueA : Controller
    {
        public class TenantA
        {
            public PersonA Owner { get; set; }

            [UsedImplicitly]
            public class TenantAValidator : AbstractValidator<TenantA>
            {
                public TenantAValidator()
                {
                    RuleFor(x => x.Owner)
                        .SetValidator(x => new PersonA.PersonAValidator(/*x*/));
                }
            }
        }

        public class PersonA
        {
            public AccountA Account { get; set; }

            public class PersonAValidator : AbstractValidator<PersonA>
            {
                public PersonAValidator(/*TenantA tenant*/)
                {
                    RuleFor(x => x.Account)
                        .SetInheritanceValidator(x =>
                        {
                            x.Add(new StrictAccountA.StrictAccountAValidator(/*tenant*/));
                        });
                }
            }
        }

        public class AccountA
        {
            public string UserName { get; set; }

            [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
            public string Password { get; set; }
        }

        public class StrictAccountA : AccountA
        {
            public class StrictAccountAValidator : AbstractValidator<AccountA>
            {
                public StrictAccountAValidator(/*TenantA tenant*/)
                {
                    this.RuleFor(x => x.UserName)
                        .NotEmpty()
                        .MaximumLength(50);

                    this.RuleFor(x => x.Password)
                        .MaximumLength(256);
                }
            }
        }

        [HttpPost("[action]")]
        public ActionResult<TenantA> AddTenantA(TenantA tenant)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            return tenant;
        }
    }

    public class TenantA
    {
    }
}
```

However, when passing an object to an inheritance validator, the NotEmpty and MaxLength rules are not emitted in swagger.json:
```
using FluentValidation;
using JetBrains.Annotations;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace SampleWebApi.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class IssueB : Controller
    {
        public class TenantB
        {
            public PersonB Owner { get; set; }

            [UsedImplicitly]
            public class TenantBValidator : AbstractValidator<TenantB>
            {
                public TenantBValidator()
                {
                    RuleFor(x => x.Owner)
                        .SetValidator(x => new PersonB.PersonBValidator(x));
                }
            }
        }

        public class PersonB
        {
            public AccountB Account { get; set; }

            public class PersonBValidator : AbstractValidator<PersonB>
            {
                public PersonBValidator(TenantB tenant)
                {
                    RuleFor(x => x.Account)
                        .SetInheritanceValidator(x =>
                        {
                            x.Add(new StrictAccountB.StrictAccountBValidator(tenant));
                        });
                }
            }
        }

        public class AccountB
        {
            public string UserName { get; set; }

            [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
            public string Password { get; set; }
        }

        public class StrictAccountB : AccountB
        {
            public class StrictAccountBValidator : AbstractValidator<AccountB>
            {
                public StrictAccountBValidator(TenantB tenant)
                {
                    this.RuleFor(x => x.UserName)
                        .NotEmpty()
                        .MaximumLength(50);

                    this.RuleFor(x => x.Password)
                        .MaximumLength(256);
                }
            }
        }

        [HttpPost("[action]")]
        public ActionResult<TenantB> AddTenantB(TenantB tenant)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            return tenant;
        }
    }

    public class TenantB
    {
    }
}
```

![image](https://user-images.githubusercontent.com/507649/135376951-124968c3-ed98-42d6-9ab4-4370a0248605.png)

Any ideas?

Thank you.

**Comment by icnocop** [comment]
When debugging, the following exception is thrown and I see it in the Debug Output window:
```
MicroElements.Swashbuckle.FluentValidation.FluentValidationRules: Warning: GetValidator for type 'SampleWebApi.Controllers.IssueB+AccountB' fails.

System.InvalidOperationException: Unable to resolve service for type 'SampleWebApi.Controllers.IssueB+TenantB' while attempting to activate 'SampleWebApi.Controllers.IssueB+StrictAccountB+StrictAccountBValidator'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.<>c__DisplayClass7_0.<GetCallSite>b__0(Type type)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at MicroElements.Swashbuckle.FluentValidation.HttpContextServiceProviderValidatorFactory.CreateInstance(Type validatorType) in C:\github\icnocop\MicroElements.Swashbuckle.FluentValidation\src\MicroElements.Swashbuckle.FluentValidation\AspNetCore\HttpContextServiceProviderValidatorFactory.cs:line 30
   at FluentValidation.ValidatorFactoryBase.GetValidator(Type type) in C:\Projects\FluentValidation\src\FluentValidation\ValidatorFactoryBase.cs:line 41
   at MicroElements.Swashbuckle.FluentValidation.FluentValidationRules.Apply(OpenApiSchema schema, SchemaFilterContext context) in C:\github\icnocop\MicroElements.Swashbuckle.FluentValidation\src\MicroElements.Swashbuckle.FluentValidation\Swashbuckle\FluentValidationRules.cs:line 92
Exception thrown: 'System.InvalidOperationException' in Microsoft.Extensions.DependencyInjection.dll
```

**Comment by icnocop** [comment]
This works in an MVC `Controller`, but the `OnActionExecutionAsync` method isn't available to override in a web API controller deriving from `ControllerBase`.

**Comment by petriashev** [comment]
You can do the same with IAsyncActionFilter

**Comment by icnocop** [comment]
Thank you.

I've tried using an action filter, but FluentValidation runs during the model binding process so the action filter doesn't have a chance to run before validation.

From https://github.com/FluentValidation/FluentValidation/issues/1607#issuecomment-754120378:

> FluentValidation runs during ASP.NET's model binding process. You'd need to write a custom model binder if you want to customize this process (not a filter).

From https://docs.microsoft.com/en-us/aspnet/core/mvc/controllers/filters?view=aspnetcore-3.1:

![filter-pipeline-2](https://user-images.githubusercontent.com/507649/139916706-a4b62035-de4f-4a70-9862-5572d9c2024b.png)

**Comment by petriashev** [comment]
yes it's true
I will try to create a sample.

**Comment by petriashev** [comment]
Other opportunity is to disable auto validation and validate in own filter after context is built

**Comment by icnocop** [comment]
Thank you.

I was able to resolve the issue as follows:
1. Set `fluentValidationMvcConfiguration.ImplicitlyValidateChildProperties = false;` in `Startup.cs`.
2. Implement `IValidatorInterceptor` in the top-level validator:
```
public ValidationResult AfterAspNetValidation(ActionContext actionContext, IValidationContext validationContext, ValidationResult result)
{
    return result;
}

public IValidationContext BeforeAspNetValidation(ActionContext actionContext, IValidationContext commonContext)
{
    // get model
    MyModel model = commonContext.InstanceToValidate as MyModel;

    // set model in accessor
    IMyAccessor myAccessor = actionContext.HttpContext.RequestServices.GetService<IMyAccessor>();
    myAccessor.MyModel = model;

    return commonContext;
}
```
3. Manually call `SetValidator` for child properties.
